### ISSUE TITLE
TraSMAPy command line argument dependency

### ISSUE THREAD

**Issue by Telmooo** [JoaoCostaIFG/TraSMAPy#7]
TraSMAPy class on its initialization calls the function `_startSimulation`, which in turn, calls a function to gather arguments from the command line using `optparse`.

This behaviour generates issues if trying to use command line arguments for another application that is depending on TraSMAPy, as `optparse` that is created on TraSMAPy won't recognize custom arguments used on the other program.

Perhaps, TraSMAPy shouldn't depend on command line arguments, or have an alternative way to initialize that doesn't depend on it.

On side note:
[optparse](https://docs.python.org/3/library/optparse.html) has been depecrated since Python 3.2, and as the version specified on the package is `>=3.7`, [argparse](https://docs.python.org/3/library/argparse.html#module-argparse) should be used instead.

**Comment by JoaoCostaIFG** [comment]
Solved
